// Shared configuration for ImgPrompt extension.
// Loaded as a classic script so it can be reused by options pages and service workers.

globalThis.ImgPromptConfig = {
  DEFAULT_SETTINGS: {
    apiEndpoint: "https://api.openai.com/v1/chat/completions",
    apiKey: "",
    model: "gpt-5-mini",
    requestFormat: "auto",
    anthropicVersion: "2023-06-01",
    hoverButtonEnabled: true,
    snippingShortcutEnabled: true,
    uiLanguage: "zh",
    maxImageEdge: 1024,
    systemPrompt:
      "You are a professional image prompt engineer. Analyze the image and return strict JSON with keys zh and en. Both values must be detailed generation prompts covering subject, composition, style, lighting, camera/lens clues, color palette, materials, background, mood, quality hints, and the image aspect ratio. Keep zh natural and fluent Chinese. Keep en optimized for image generation models. Do not wrap the JSON in markdown.",
    userPrompt:
      "Please perform a structural breakdown of this image. Identify core visual primitives, spatial layout logic, and the color harmonic system. Include the exact image aspect ratio. If details are obscured, extrapolate based on contextual consistency. Output only JSON like {\"zh\":\"...\", \"en\":\"...\"}.",
    temperature: 1
  },

  USER_PROMPT_PRESETS: {
    general: "Please perform a structural breakdown of this image. Identify core visual primitives, spatial layout logic, and the color harmonic system. Include the exact image aspect ratio. If details are obscured, extrapolate based on contextual consistency. Output only JSON like {\"zh\":\"...\", \"en\":\"...\"}.",
    photo: "Analyze this photograph using high-fidelity technical parameters. Extract light quality (specular vs. diffused), color temperature (Kelvin), contrast dynamics, lens optics (focal length, compression, chromatic aberration), and aperture effects (depth of field, bokeh shape). Specify filmic attributes including grain density, color grading (LUT), and sensor-level detail. Output only JSON like {\"zh\":\"...\", \"en\":\"...\"}.",
    cg: "Deconstruct the digital craftsmanship and artistic medium. Focus on brushstroke dynamics (impasto, glazing), color theory application, and light-matter interaction (subsurface scattering, global illumination). Identify the rendering pipeline (ray tracing, volumetric effects) and specific stylistic influences (art movement, era). Output only JSON like {\"zh\":\"...\", \"en\":\"...\"}.",
    design: "Analyze the visual communication system and information architecture. Focus on typographic hierarchy (weight, kerning), grid-based alignment, negative space utilization, and iconographic style. Define the color contrast ratios and the specific design movement (e.g., International Typographic Style, Bauhaus, Modernism). Output only JSON like {\"zh\":\"...\", \"en\":\"...\"}.",
    assets3d: "Examine the 3D model's technical topology and material logic. Focus on PBR map accuracy (albedo, roughness, metalness, normal), mesh density, silhouette integrity, and surface imperfection patterns (scratches, dust). Assume the asset is isolated for engine integration. Output only JSON like {\"zh\":\"...\", \"en\":\"...\"}.",
    product: "Evaluate the commercial staging and hero-shot composition. Focus on the lighting rig (key, fill, rim, and kickers), material premiumness (surface finish, reflections), and macro-level branding details. Analyze the environmental context and the psychological positioning (e.g., minimalist, high-tech, organic). Output only JSON like {\"zh\":\"...\", \"en\":\"...\"}.",
    ui: "Deconstruct the interface architecture and design system logic. Identify component library characteristics (e.g., Atomic Design, Material You, shadcn/ui), navigation patterns, and interaction affordances. Extract design tokens including precise color palettes (primary, semantic, surface), corner radius (px), elevation levels (shadows), and typography scale. Define the interface style (e.g., Glassmorphism, Neumorphism, SaaS-minimal, Bento-grid) and functional hierarchy. Output only JSON like {\"zh\":\"...\", \"en\":\"...\"}."
  },

  UI_STRINGS: {
    zh: {
      preparing: "准备中",
      locatingImage: "正在定位图片",
      generating: "生成中",
      completed: "已完成",
      generationComplete: "生成完成",
      subtitle: "图片转提示词",
      stopped: "已停止",
      stopGeneration: "已停止生成",
      failed: "失败",
      generationFailed: "生成失败",
      waitingToStart: "等待开始",
      stopButton: "停止生成",
      placeholder: "生成后的提示词会显示在这里，可直接修改。",
      zhBtn: "中文",
      enBtn: "English",
      copyBtn: "复制",
      copied: "已复制",
      copyFailed: "复制失败，请检查剪贴板权限。",
      dragCard: "拖动卡片",
      closeHover: "关闭悬浮按钮",
      unknownError: "发生未知错误",
      imageLoading: "图片加载中...",
      fetchingImage: "正在获取图片",
      callingModel: "正在调用模型",
      organizingPrompts: "正在整理提示词",
      fetchFailed: "未能获取图片内容，请尝试在图片加载完成后重试。",
      modelFailed: "模型请求失败",
      emptyContent: "模型返回内容为空，无法生成提示词。",
      noJson: "模型返回的不是有效 JSON，请调整 system prompt 后重试。",
      missingFields: "模型返回缺少 zh/en 字段。",
      base64Failed: "图片处理失败：无法获取图片的二进制数据进行 AI 分析。请尝试换一张图或检查网络连接。",
      historyTitle: "历史记录",
      historyEmpty: "暂无历史记录",
      historyClear: "清空全部",
      historyCopy: "复制",
      historyDelete: "删除",
      historyCopied: "已复制",
      historyLoaded: "已复制到剪贴板 ✓"
    },
    en: {
      preparing: "Preparing",
      locatingImage: "Locating image",
      generating: "Generating",
      completed: "Completed",
      generationComplete: "Generation complete",
      subtitle: "Image to Prompt",
      stopped: "Stopped",
      stopGeneration: "Generation stopped",
      failed: "Failed",
      generationFailed: "Generation failed",
      waitingToStart: "Waiting to start",
      stopButton: "Stop generation",
      placeholder: "Generated prompts will appear here. You can edit them directly.",
      zhBtn: "ZH",
      enBtn: "EN",
      copyBtn: "Copy",
      copied: "Copied",
      copyFailed: "Copy failed. Please check clipboard permissions.",
      dragCard: "Drag to move",
      closeHover: "Close hover button",
      unknownError: "Unknown error occurred",
      imageLoading: "Loading image...",
      fetchingImage: "Fetching image",
      callingModel: "Calling model",
      organizingPrompts: "Organizing prompts",
      fetchFailed: "Failed to fetch image. Please try again after the image has fully loaded.",
      modelFailed: "Model request failed",
      emptyContent: "Model returned empty content. Failed to generate prompts.",
      noJson: "Model returned invalid JSON. Please adjust your system prompt and try again.",
      missingFields: "Model response missing zh/en fields.",
      base64Failed: "Image processing failed: Could not encode image to base64 for AI analysis. Please try another image or check your connection.",
      historyTitle: "History",
      historyEmpty: "No history yet",
      historyClear: "Clear all",
      historyCopy: "Copy",
      historyDelete: "Delete",
      historyCopied: "Copied",
      historyLoaded: "Copied to clipboard ✓"
    }
  },

  SETTINGS_I18N: {
    zh: {
      "imgprompt-title": "ImgPrompt",
      "imgprompt-subtitle": "图片转提示词",
      "connection-section-title": "连接设置",
      "connection-section-note": "填入接口地址、模型和密钥。",
      "endpoint-label": "API 接口地址",
      "endpoint-hint": "常见兼容接口为 /v1/chat/completions",
      "model-label": "模型名称",
      "model-hint": "例如 gpt-5-mini 或 gemini-2.5-pro",
      "key-label": "API 密钥",
      "key-hint": "仅保存在本地浏览器中",
      "prompt-section-title": "提示词设置",
      "prompt-section-note": "选择预设场景，或自定义具体的提取任务。",
      "system-prompt-label": "System Prompt",
      "user-prompt-label": "User Prompt",
      "experience-section-title": "使用体验",
      "experience-section-note": "控制插件在网页中的交互方式。",
      "toggle-hover-title": "悬浮 PicPrompt 按钮",
      "toggle-hover-note": "鼠标移到图片上时显示快捷入口。",
      "toggle-snipping-title": "截屏提取提示词",
      "toggle-snipping-note": "使用快捷键对网页进行框选截图分析。",
      "shortcut-hint": "默认快捷键：Alt / Option + S 。如需修改，请前往 chrome://extensions/shortcuts",
      "language-label": "面板语言",
      "language-note": "切换设置面板的显示语言。",
      "compatibility-section-title": "兼容性设置",
      "compatibility-section-note": "如果遇到 400 报错，请尝试调整以下设置。",
      "resolution-label": "图片分辨率限制",
      "resolution-note": "降低分辨率可减小请求体积，防止接口超时或拒绝。",
      "reset-button": "恢复默认",
      "preset-general": "通用",
      "preset-photo": "📸 摄影",
      "preset-cg": "🎨 插画CG",
      "preset-design": "📐 平面设计",
      "preset-ui": "📱 界面 UI",
      "preset-3d": "🧊 游戏资产",
      "preset-product": "👕 电商产品",
      "preset-add-custom": "➕ 添加自定义",
      "custom-title-label": "模板名称",
      "custom-title-placeholder": "分享您的提示词名称",
      "custom-save-btn": "保存",
      "custom-cancel-btn": "取消",
      "custom-delete-btn": "🗑️ 删除",
      "footer-contact": "联系开发者："
    },
    en: {
      "imgprompt-title": "ImgPrompt",
      "imgprompt-subtitle": "Image to Prompt",
      "connection-section-title": "Connection",
      "connection-section-note": "Enter API endpoint, model, and key.",
      "endpoint-label": "API Endpoint",
      "endpoint-hint": "Common compatible interface: /v1/chat/completions",
      "model-label": "Model",
      "model-hint": "e.g., gpt-5-mini or gemini-2.5-pro",
      "key-label": "API Key",
      "key-hint": "Saved locally in browser only",
      "prompt-section-title": "Prompt",
      "prompt-section-note": "Choose a preset or customize the specific task.",
      "system-prompt-label": "System Prompt",
      "user-prompt-label": "User Prompt",
      "experience-section-title": "Experience",
      "experience-section-note": "Control how the hover entry appears.",
      "toggle-hover-title": "Hover PicPrompt Button",
      "toggle-hover-note": "Show shortcut entry when hovering over images.",
      "toggle-snipping-title": "Shortcut Snipping",
      "toggle-snipping-note": "Use shortcut to select and analyze any area on the page.",
      "shortcut-hint": "Default: Alt / Option + S. To modify, go to chrome://extensions/shortcuts",
      "language-label": "Panel Language",
      "language-note": "Switch the language of this settings panel.",
      "compatibility-section-title": "Compatibility",
      "compatibility-section-note": "If you encounter 400 errors, try adjusting these settings.",
      "resolution-label": "Max Image Resolution",
      "resolution-note": "Lowering resolution reduces payload size and avoids timeouts.",
      "reset-button": "Reset to Defaults",
      "preset-general": "General",
      "preset-photo": "📸 Photo",
      "preset-cg": "🎨 Illust",
      "preset-design": "📐 Design",
      "preset-ui": "📱 UI Design",
      "preset-3d": "🧊 3D Asset",
      "preset-product": "👕 Product",
      "preset-add-custom": "➕ Add Custom",
      "custom-title-label": "Template Name",
      "custom-title-placeholder": "Name your prompt template",
      "custom-save-btn": "Save",
      "custom-cancel-btn": "Cancel",
      "custom-delete-btn": "🗑️ Delete",
      "footer-contact": "Contact Developer: "
    }
  },

  ERROR_CODES: {
    NETWORK_ERROR: "NETWORK_ERROR",
    IMAGE_FETCH_FAILED: "IMAGE_FETCH_FAILED",
    IMAGE_PROCESSING_FAILED: "IMAGE_PROCESSING_FAILED",
    API_AUTH_FAILED: "API_AUTH_FAILED",
    API_RATE_LIMITED: "API_RATE_LIMITED",
    API_TIMEOUT: "API_TIMEOUT",
    API_INVALID_RESPONSE: "API_INVALID_RESPONSE",
    JSON_PARSE_FAILED: "JSON_PARSE_FAILED",
    MISSING_FIELDS: "MISSING_FIELDS",
    CANCELED: "CANCELED",
    UNKNOWN: "UNKNOWN"
  },

  ERROR_MESSAGES: {
    zh: {
      "NETWORK_ERROR": "网络连接失败，请检查网络后重试。",
      "IMAGE_FETCH_FAILED": "无法获取图片，请确认图片链接有效且可访问。",
      "IMAGE_PROCESSING_FAILED": "图片处理失败，请尝试换一张图片或调整分辨率设置。",
      "API_AUTH_FAILED": "API 密钥无效或已过期，请检查设置中的 API Key。",
      "API_RATE_LIMITED": "API 调用次数已达上限，请稍后再试或升级配额。",
      "API_TIMEOUT": "API 请求超时，请检查网络连接或降低图片分辨率。",
      "API_INVALID_RESPONSE": "API 返回了意外结果，请检查模型配置或更换模型。",
      "JSON_PARSE_FAILED": "模型返回的内容无法解析，请调整 System Prompt 确保输出纯 JSON。",
      "MISSING_FIELDS": "模型返回缺少必需的 zh/en 字段，请检查 System Prompt。",
      "CANCELED": "已停止生成。",
      "UNKNOWN": "发生未知错误，请重试。"
    },
    en: {
      "NETWORK_ERROR": "Network connection failed. Please check your connection and try again.",
      "IMAGE_FETCH_FAILED": "Unable to fetch image. Please verify the image URL is valid and accessible.",
      "IMAGE_PROCESSING_FAILED": "Image processing failed. Please try another image or lower the resolution.",
      "API_AUTH_FAILED": "Invalid or expired API key. Please check your API Key in settings.",
      "API_RATE_LIMITED": "API rate limit reached. Please try again later or upgrade your quota.",
      "API_TIMEOUT": "API request timed out. Check your connection or lower image resolution.",
      "API_INVALID_RESPONSE": "API returned unexpected results. Check model configuration or try another model.",
      "JSON_PARSE_FAILED": "Could not parse model output. Adjust System Prompt to ensure pure JSON output.",
      "MISSING_FIELDS": "Model response missing required zh/en fields. Check your System Prompt.",
      "CANCELED": "Generation stopped.",
      "UNKNOWN": "An unknown error occurred. Please try again."
    }
  },

  POSTHOG_PROJECT_KEY: atob("cGhjX3dUYnlxb2FMbnNrUEZFc0t5U0xzdWRiSGFucFR6amJWOGNxWXdEM0ZWeno2"),
  POSTHOG_HOST: "https://us.i.posthog.com",
  ANALYTICS_CONFIG_KEY: "analyticsConfig"
};
