// Shared configuration for ImgPrompt extension.
// Loaded as a classic script so it can be reused by options pages and service workers.

globalThis.ImgPromptConfig = {
  // 基础提示词 - 始终使用
  BASE_USER_PROMPT: "以json格式描述这幅图,描述准确复刻原始图像所需的所有方面,包括主体、视角构图、风格、光线、图片比例、有关物品、服装、发型、复杂细节、配饰、摄影器材、环境、身体姿势以及任何其他相关元素的具体信息,确保能够精确地重现原始图像的每一个细节。要求输出json格式提示词,字数750字以内。",

  DEFAULT_SETTINGS: {
    apiEndpoint: "https://api.openai.com/v1/chat/completions",
    apiKey: "",
    model: "gpt-5-mini",
    requestFormat: "auto",
    anthropicVersion: "2023-06-01",
    hoverButtonEnabled: true,
    snippingShortcutEnabled: true,
    uiLanguage: "zh",
    maxImageEdge: 1024,
    recreateMode: false,
    systemPrompt:
      "You are an expert reverse prompt engineer specializing in ultra-accurate image recreation. Your task is to analyze the image with extreme precision and generate JSON prompts that will reproduce the exact same image when fed to AI image generators.\n\nCRITICAL REQUIREMENTS:\n- Describe ALL aspects needed to accurately recreate the original image\n- Include: subject, perspective/composition, style, lighting, aspect ratio, objects, clothing, hairstyle, intricate details, accessories, photography equipment, environment, body posture, and any other relevant elements\n- Provide specific, detailed information for each element\n- Ensure every detail is captured to enable precise recreation of the original image\n\nOUTPUT FORMAT:\n- zh: Chinese prompt, natural and fluent, optimized for Chinese AI tools\n- en: English prompt, optimized for AI image generation models\n\nCONSTRAINTS:\n- Output ONLY valid JSON with zh and en keys\n- Each prompt must be under 750 Chinese characters / 750 English words\n- Do not wrap JSON in markdown\n- Be concise but comprehensive\n- Focus on visual elements that directly impact image generation",
    userPrompt:
      "以json格式描述这幅图,描述准确复刻原始图像所需的所有方面,包括主体、视角构图、风格、光线、图片比例、有关物品、服装、发型、复杂细节、配饰、摄影器材、环境、身体姿势以及任何其他相关元素的具体信息,确保能够精确地重现原始图像的每一个细节。要求输出json格式提示词,字数750字以内。",
    temperature: 1
  },

  USER_PROMPT_PRESETS: {
    general: "Please perform a comprehensive structural breakdown of this image for exact recreation:\n\n1. SUBJECT ANALYSIS: Main subject(s), pose, expression, clothing, accessories, hair, makeup\n2. COMPOSITION: Camera angle (eye-level/high-angle/low-angle), perspective, framing, depth layers\n3. LIGHTING: Direction, intensity, color temperature (warm/cool), shadows, highlights, reflections\n4. COLOR PALETTE: Dominant colors, accent colors, color harmony, saturation, mood\n5. MATERIALS/TEXTURES: Fabric types, surface properties (matte/glossy/reflective), details\n6. BACKGROUND: Environment, objects, spatial depth, atmospheric effects, weather\n7. ARTISTIC STYLE: Medium (photo/digital/painting/illustration), technique, art movement\n8. QUALITY ASPECTS: Sharpness, detail level, noise/grain, resolution hints\n9. EMOTION/ATMOSPHERE: Mood, feeling, narrative context, psychological impact\n10. TECHNICAL SPECS: Aspect ratio, estimated dimensions, format type\n\nOutput comprehensive JSON with zh, en, negative_zh, negative_en fields optimized for AI image generation with ultra-high fidelity. Do not wrap in markdown.",
    photo: "Analyze this photograph using high-fidelity technical parameters for exact recreation:\n\n1. CAMERA SETTINGS: Focal length (35mm/50mm/85mm/etc.), aperture (f/1.4, f/2.8, etc.), shutter speed hints, ISO\n2. LENS CHARACTERISTICS: Compression, distortion, chromatic aberration, vignetting, bokeh shape\n3. LIGHTING ANALYSIS: Key light direction/intensity, fill light, rim/backlight, reflectors, natural vs. artificial\n4. COLOR GRADING: Color temperature (Kelvin), tint, split toning, LUT style, film emulation (Kodak/Fuji)\n5. SENSOR CHARACTERISTICS: Grain density, dynamic range, highlight roll-off, shadow detail, noise pattern\n6. COMPOSITION TECHNIQUES: Rule of thirds, leading lines, symmetry, depth of field, focus stacking\n7. SUBJECT DETAILS: Expression, pose, micro-expressions, clothing textures, accessories\n8. ENVIRONMENT: Background blur quality (bokeh), atmospheric haze, weather conditions\n9. POST-PROCESSING: Dodge/burn, clarity, vibrance, saturation adjustments, sharpening\n10. ASPECT RATIO: Exact dimensions and crop\n\nInclude negative prompts to avoid: blurry, overexposed, underexposed, chromatic aberration artifacts. Output JSON with zh, en, negative_zh, negative_en fields.",
    cg: "Deconstruct the digital artwork and illustration with extreme precision:\n\n1. ARTISTIC MEDIUM: Digital painting, vector art, pixel art, 3D render, mixed media\n2. BRUSHWORK ANALYSIS: Stroke type (impasto/glazing/scumbling), brush texture, paint thickness\n3. COLOR THEORY: Color scheme (complementary/analogous/triadic), value structure, saturation balance\n4. LIGHT-MATTER INTERACTION: Subsurface scattering, global illumination, ray tracing quality, volumetric effects\n5. RENDERING PIPELINE: 2D vs 3D, rendering engine hints (Octane/Redshift/Arnold), post-processing\n6. STYLISTIC INFLUENCES: Art movement (Impressionism/Art Nouveau/Cyberpunk/etc.), artist references\n7. COMPOSITION DYNAMICS: Focal points, visual flow, rule of thirds, golden ratio, symmetry\n8. TEXTURE QUALITY: Surface details, material properties (metal/fabric/skin), micro-contrast\n9. ATMOSPHERIC EFFECTS: Fog, particles, lens flare, chromatic aberration, bloom\n10. TECHNICAL SPECS: Resolution hints, aspect ratio, color space\n\nOutput comprehensive JSON with zh, en, negative_zh, negative_en fields for ultra-accurate recreation.",
    design: "Analyze the graphic design with professional precision:\n\n1. TYPOGRAPHIC SYSTEM: Font families, weights, sizes, kerning, leading, hierarchy levels\n2. GRID STRUCTURE: Column count, margins, gutters, alignment (left/center/right/justified)\n3. COLOR SYSTEM: Primary palette, secondary colors, accent colors, contrast ratios (WCAG)\n4. LAYOUT COMPOSITION: Visual hierarchy, focal points, reading flow (Z-pattern/F-pattern)\n5. GRAPHIC ELEMENTS: Icons, illustrations, photos, patterns, decorative elements\n6. WHITE SPACE: Negative space utilization, breathing room, padding ratios\n7. DESIGN MOVEMENT: Bauhaus, Swiss Style, Memphis, Minimalism, Brutalism, etc.\n8. BRANDING ELEMENTS: Logo placement, brand colors, visual identity consistency\n9. FUNCTIONAL ASPECTS: Call-to-action visibility, information architecture, user flow\n10. TECHNICAL SPECS: Format (print/web/mobile), resolution, color mode (RGB/CMYK)\n\nOutput JSON with zh, en, negative_zh, negative_en fields optimized for design recreation.",
    assets3d: "Examine the 3D asset with technical precision for game engine integration:\n\n1. TOPOLOGY ANALYSIS: Mesh density, polygon count, edge flow, quad vs. tri dominance\n2. PBR MATERIALS: Albedo/base color, roughness map, metallic map, normal map, displacement\n3. SURFACE IMPERFECTIONS: Scratches, dust, fingerprints, wear patterns, weathering\n4. SILHOUETTE INTEGRITY: Shape language, proportions, scale references, recognizability\n5. UV MAPPING: UV layout efficiency, texel density, seam placement, texture resolution\n6. LIGHTING SETUP: Three-point lighting, HDRI environment, IBL (Image-Based Lighting)\n7. RENDER SETTINGS: Sampling rate, denoising, ray bounces, caustics, subsurface scattering\n8. ANIMATION READINESS: Rigging hints, joint placement, deformation quality\n9. OPTIMIZATION LEVEL: LOD (Level of Detail) hints, texture compression, poly count optimization\n10. ENGINE COMPATIBILITY: Unity/Unreal/Blender hints, format preferences\n\nOutput JSON with zh, en, negative_zh, negative_en fields for accurate 3D asset recreation.",
    product: "Evaluate the product photography with commercial staging precision:\n\n1. LIGHTING RIG: Key light (position/intensity), fill light, rim light, kickers, reflectors, diffusers\n2. MATERIAL PREMIUMNESS: Surface finish (matte/glossy/metallic), reflections, texture detail, micro-scratches\n3. COMPOSITION TYPE: Hero shot, lifestyle, flat lay, isometric, exploded view\n4. BRANDING DETAILS: Logo clarity, packaging design, label text, color accuracy\n5. ENVIRONMENTAL CONTEXT: Studio white, lifestyle setting, contextual props, background blur\n6. PSYCHOLOGICAL POSITIONING: Luxury, affordable, eco-friendly, high-tech, organic, minimalist\n7. MACRO DETAILS: Stitching, seams, buttons, zippers, embossing, material transitions\n8. COLOR SCIENCE: Product color accuracy, color temperature, white balance, color grading\n9. STYLING ELEMENTS: Props, staging, composition aids, visual anchors\n10. COMMERCIAL SPECS: Aspect ratio for e-commerce, resolution, format (square/vertical/horizontal)\n\nInclude negative prompts: low quality product photo, poor lighting, blurry details. Output JSON with zh, en, negative_zh, negative_en fields.",
    ui: "Deconstruct the UI/UX design with design system precision:\n\n1. COMPONENT LIBRARY: Design system (Material Design, Human Interface, shadcn/ui, Tailwind UI, custom)\n2. NAVIGATION PATTERNS: Top bar, sidebar, bottom nav, breadcrumbs, hamburger menu, tabs\n3. INTERACTION AFFORDANCES: Buttons, inputs, toggles, sliders, checkboxes, dropdowns, cards\n4. DESIGN TOKENS: \n   - Colors: Primary, secondary, semantic (success/warning/error), surface, text\n   - Typography: Font family, scale (h1-h6, body, caption), weights\n   - Spacing: 4px/8px grid, padding ratios, gap sizes\n   - Elevation: Shadow values, z-index layers, backdrop blur\n   - Borders: Corner radius (2px/4px/8px/12px/16px/full), stroke width\n5. LAYOUT ARCHITECTURE: Grid system, responsive breakpoints, container widths\n6. INTERFACE STYLE: Glassmorphism, Neumorphism, Flat Design, Skeuomorphism, Bento Grid, SaaS-minimal\n7. FUNCTIONAL HIERARCHY: Primary actions, secondary actions, destructive actions, disabled states\n8. ACCESSIBILITY: Contrast ratios, focus indicators, screen reader considerations\n9. STATE VARIATIONS: Default, hover, active, disabled, loading, error, success\n10. PLATFORM CONTEXT: Web, iOS, Android, Desktop, Responsive\n\nOutput JSON with zh, en, negative_zh, negative_en fields for precise UI recreation.",
    anime: "Analyze this anime/manga illustration with otaku-level precision:\n\n1. CHARACTER DESIGN: \n   - Hair: Style, color, length, accessories (ribbons/clips/flowers)\n   - Eyes: Shape (tsurime/tareme), color, highlights, eyelashes\n   - Face: Expression, blush, mouth shape, facial structure\n   - Body: Proportions (chibi/realistic), pose, gesture, body language\n2. CLOTHING & ACCESSORIES:\n   - Outfit: School uniform, casual, fantasy armor, magical girl, etc.\n   - Details: Folds, pleats, accessories (necklaces/bracelets/rings)\n   - Shoes: Sneakers, boots, sandals, traditional footwear\n3. ART STYLE: \n   - Shading: Cel-shaded, gradient, soft shading, hard-edged\n   - Lineart: Thick/thin, colored/outlined, sketch style\n   - Effects: Sparkles, aura, speed lines, impact frames\n4. BACKGROUND ELEMENTS: School, city, fantasy world, nature, room interior\n5. COLOR PALETTE: Vibrant, pastel, muted, monochrome, seasonal theme\n6. COMPOSITION: Rule of thirds, dynamic angle, close-up, full body, chibi\n7. ANIME TROPES: Tsundere pose, victory sign, blush, tears, action stance\n8. ARTIST STYLE HINTS: Kyoto Animation, Ufotable, MAPPA, Trigger, etc.\n9. ASPECT RATIO: Common anime ratios (16:9, 4:3, vertical mobile)\n10. QUALITY TAGS: Masterpiece, best quality, highly detailed\n\nInclude negative prompts: lowres, bad anatomy, bad hands, missing fingers, extra limbs, poorly drawn face, mutation, deformed, blurry, bad anatomy, disfigured. Output JSON with zh, en, negative_zh, negative_en fields.",
    architecture: "Analyze this architectural/interior design with technical precision:\n\n1. ARCHITECTURAL STYLE: Modern, Classical, Gothic, Art Deco, Brutalist, Minimalist, Contemporary, etc.\n2. STRUCTURAL ELEMENTS: Columns, beams, arches, domes, facades, roof types\n3. MATERIAL PALETTE: Concrete, glass, steel, wood, brick, stone, marble, etc.\n4. SPATIAL LAYOUT: Floor plan hints, room flow, open vs. closed spaces, circulation\n5. LIGHTING DESIGN: Natural light (windows/skylights), artificial lighting (pendants/recessed/track)\n6. FURNITURE & DECOR: Style (mid-century modern, industrial, Scandinavian), arrangement, focal pieces\n7. COLOR SCHEME: Wall colors, accent walls, material tones, complementary schemes\n8. PERSPECTIVE & CAMERA: Eye-level, bird's eye, worm's eye, one-point/two-point perspective\n9. ATMOSPHERE & MOOD: Cozy, grand, minimalist, dramatic, serene, vibrant\n10. ENVIRONMENTAL CONTEXT: Urban, rural, interior, exterior, landscape integration\n11. TECHNICAL DETAILS: Scale references, proportions, symmetry, golden ratio\n12. LANDSCAPE ELEMENTS: Gardens, pools, terraces, pathways, outdoor furniture\n\nInclude negative prompts: distorted perspective, warped lines, unrealistic proportions. Output JSON with zh, en, negative_zh, negative_en fields.",
    food: "Analyze this food photography with culinary and styling precision:\n\n1. DISH COMPOSITION: Plating style (rustic/elegant/casual), arrangement, portion size\n2. INGREDIENTS VISIBLE: Main components, garnishes, sauces, textures (crispy/creamy/juicy)\n3. COOKING TECHNIQUE: Grilled, fried, baked, steamed, raw, sous vide hints\n4. TABLEWARE: Plate type (ceramic/wood/slate), cutlery, glassware, napkins\n5. LIGHTING SETUP: Food photography lighting (softbox/natural/window light), reflections\n6. CAMERA ANGLE: Overhead (flat lay), 45-degree, eye-level, macro close-up\n7. COLOR PALETTE: Food colors, plate colors, background, complementary schemes\n8. STYLING PROPS: Ingredients scattered, utensils, flowers, textiles, boards\n9. MOOD & CONTEXT: Restaurant, home cooking, magazine-style, social media, cookbook\n10. TEXTURE DETAILS: Steam, drips, crust, glaze, crumb structure, surface shine\n11. DEPTH OF FIELD: Sharp focus area, bokeh background, selective focus\n12. ASPECT RATIO: Square (Instagram), vertical (Pinterest), horizontal (website)\n\nInclude negative prompts: blurry food, unappetizing, poor lighting, messy plating. Output JSON with zh, en, negative_zh, negative_en fields.",
    portrait: "Analyze this portrait photograph with professional photography precision:\n\n1. SUBJECT APPEARANCE: \n   - Demographics: Age range, ethnicity, gender expression\n   - Facial features: Face shape, eye color, nose, lips, distinctive features\n   - Expression: Smile, serious, contemplative, joyful, intense, relaxed\n   - Hair: Style, color, length, texture, styling products\n2. POSE & BODY LANGUAGE: \n   - Head position: Tilt, angle, chin position\n   - Body: Turned, facing forward, leaning, sitting, standing\n   - Hands: Position, gesture, props held\n   - Posture: Confident, relaxed, tense, casual, formal\n3. CLOTHING & STYLING:\n   - Outfit: Style (business/casual/avant-garde), colors, patterns\n   - Accessories: Jewelry, glasses, hats, scarves, watches\n   - Makeup: Natural, dramatic, editorial, no-makeup look\n4. LIGHTING SETUP:\n   - Type: Studio (Rembrandt/Butterfly/Split/Loop), natural, mixed\n   - Quality: Hard, soft, diffused, directional\n   - Modifiers: Softbox, umbrella, beauty dish, reflector, flags\n   - Ratio: High key, low key, dramatic contrast\n5. BACKGROUND & ENVIRONMENT:\n   - Studio: Seamless backdrop, colored paper, cyclorama\n   - Location: Urban, nature, architectural, interior\n   - Treatment: Blurred, sharp, patterned, gradient\n6. CAMERA & LENS:\n   - Focal length: 50mm (natural), 85mm (portrait), 135mm (compressed)\n   - Aperture: f/1.4-f/2.8 (shallow DOF), f/5.6-f/8 (sharp)\n   - Angle: Eye-level, slightly above, low angle\n7. COLOR GRADING: \n   - Tone: Warm, cool, neutral, split-toned\n   - Style: Film emulation, cinematic, vintage, modern clean\n8. RETOUCHING LEVEL: Natural, beauty retouch, editorial, high fashion, gritty\n9. MOOD & NARRATIVE: Professional, intimate, editorial, fashion, documentary\n10. ASPECT RATIO: Standard portrait (4:5), social media (1:1), cinematic (16:9)\n\nInclude negative prompts: blurry, low quality, poorly lit, distorted face, bad anatomy. Output JSON with zh, en, negative_zh, negative_en fields."
  },

  UI_STRINGS: {
    zh: {
      preparing: "准备中",
      locatingImage: "正在定位图片",
      generating: "生成中",
      completed: "已完成",
      generationComplete: "生成完成",
      subtitle: "图片转提示词",
      stopped: "已停止",
      stopGeneration: "已停止生成",
      failed: "失败",
      generationFailed: "生成失败",
      waitingToStart: "等待开始",
      stopButton: "停止生成",
      placeholder: "生成后的提示词会显示在这里，可直接修改。",
      zhBtn: "中文",
      enBtn: "English",
      copyBtn: "复制",
      copied: "已复制",
      copyFailed: "复制失败，请检查剪贴板权限。",
      dragCard: "拖动卡片",
      closeHover: "关闭悬浮按钮",
      unknownError: "发生未知错误",
      imageLoading: "图片加载中...",
      fetchingImage: "正在获取图片",
      callingModel: "正在调用模型",
      organizingPrompts: "正在整理提示词",
      fetchFailed: "未能获取图片内容，请尝试在图片加载完成后重试。",
      modelFailed: "模型请求失败",
      emptyContent: "模型返回内容为空，无法生成提示词。",
      noJson: "模型返回的不是有效 JSON，请调整 system prompt 后重试。",
      missingFields: "模型返回缺少 zh/en 字段。",
      base64Failed: "图片处理失败：无法获取图片的二进制数据进行 AI 分析。请尝试换一张图或检查网络连接。",
      historyTitle: "历史记录",
      historyEmpty: "暂无历史记录",
      historyClear: "清空全部",
      historyCopy: "复制",
      historyDelete: "删除",
      historyCopied: "已复制",
      historyLoaded: "已复制到剪贴板 ✓"
    },
    en: {
      preparing: "Preparing",
      locatingImage: "Locating image",
      generating: "Generating",
      completed: "Completed",
      generationComplete: "Generation complete",
      subtitle: "Image to Prompt",
      stopped: "Stopped",
      stopGeneration: "Generation stopped",
      failed: "Failed",
      generationFailed: "Generation failed",
      waitingToStart: "Waiting to start",
      stopButton: "Stop generation",
      placeholder: "Generated prompts will appear here. You can edit them directly.",
      zhBtn: "ZH",
      enBtn: "EN",
      copyBtn: "Copy",
      copied: "Copied",
      copyFailed: "Copy failed. Please check clipboard permissions.",
      dragCard: "Drag to move",
      closeHover: "Close hover button",
      unknownError: "Unknown error occurred",
      imageLoading: "Loading image...",
      fetchingImage: "Fetching image",
      callingModel: "Calling model",
      organizingPrompts: "Organizing prompts",
      fetchFailed: "Failed to fetch image. Please try again after the image has fully loaded.",
      modelFailed: "Model request failed",
      emptyContent: "Model returned empty content. Failed to generate prompts.",
      noJson: "Model returned invalid JSON. Please adjust your system prompt and try again.",
      missingFields: "Model response missing zh/en fields.",
      base64Failed: "Image processing failed: Could not encode image to base64 for AI analysis. Please try another image or check your connection.",
      historyTitle: "History",
      historyEmpty: "No history yet",
      historyClear: "Clear all",
      historyCopy: "Copy",
      historyDelete: "Delete",
      historyCopied: "Copied",
      historyLoaded: "Copied to clipboard ✓"
    }
  },

  SETTINGS_I18N: {
    zh: {
      "imgprompt-title": "ImgPrompt",
      "imgprompt-subtitle": "图片转提示词",
      "connection-section-title": "连接设置",
      "connection-section-note": "填入接口地址、模型和密钥。",
      "endpoint-label": "API 接口地址",
      "endpoint-hint": "常见兼容接口为 /v1/chat/completions",
      "model-label": "模型名称",
      "model-hint": "例如 gpt-5-mini 或 gemini-2.5-pro",
      "key-label": "API 密钥",
      "key-hint": "仅保存在本地浏览器中",
      "prompt-section-title": "提示词设置",
      "prompt-section-note": "选择预设场景，或自定义具体的提取任务。",
      "system-prompt-label": "System Prompt",
      "user-prompt-label": "User Prompt",
      "experience-section-title": "使用体验",
      "experience-section-note": "控制插件在网页中的交互方式。",
      "toggle-hover-title": "悬浮 PicPrompt 按钮",
      "toggle-hover-note": "鼠标移到图片上时显示快捷入口。",
      "toggle-snipping-title": "截屏提取提示词",
      "toggle-snipping-note": "使用快捷键对网页进行框选截图分析。",
      "toggle-recreate-title": "高还原度模式",
      "toggle-recreate-note": "启用后将使用更详细的分析提示词,生成更精确的还原提示词(包含负面提示词和技术参数)。",
      "shortcut-hint": "默认快捷键：Alt / Option + S 。如需修改，请前往 chrome://extensions/shortcuts",
      "language-label": "面板语言",
      "language-note": "切换设置面板的显示语言。",
      "compatibility-section-title": "兼容性设置",
      "compatibility-section-note": "如果遇到 400 报错，请尝试调整以下设置。",
      "resolution-label": "图片分辨率限制",
      "resolution-note": "降低分辨率可减小请求体积，防止接口超时或拒绝。",
      "reset-button": "恢复默认",
      "preset-general": "通用",
      "preset-photo": "📸 摄影",
      "preset-cg": "🎨 插画CG",
      "preset-design": "📐 平面设计",
      "preset-ui": "📱 界面 UI",
      "preset-3d": "🧊 游戏资产",
      "preset-product": "👕 电商产品",
      "preset-anime": "🎭 动漫插画",
      "preset-architecture": "🏛️ 建筑室内",
      "preset-food": "🍜 美食摄影",
      "preset-portrait": "👤 人像摄影",
      "preset-add-custom": "➕ 添加自定义",
      "custom-title-label": "模板名称",
      "custom-title-placeholder": "分享您的提示词名称",
      "custom-save-btn": "保存",
      "custom-cancel-btn": "取消",
      "custom-delete-btn": "🗑️ 删除",
      "footer-contact": "感谢大帅锅："
    },
    en: {
      "imgprompt-title": "ImgPrompt",
      "imgprompt-subtitle": "Image to Prompt",
      "connection-section-title": "Connection",
      "connection-section-note": "Enter API endpoint, model, and key.",
      "endpoint-label": "API Endpoint",
      "endpoint-hint": "Common compatible interface: /v1/chat/completions",
      "model-label": "Model",
      "model-hint": "e.g., gpt-5-mini or gemini-2.5-pro",
      "key-label": "API Key",
      "key-hint": "Saved locally in browser only",
      "prompt-section-title": "Prompt",
      "prompt-section-note": "Choose a preset or customize the specific task.",
      "system-prompt-label": "System Prompt",
      "user-prompt-label": "User Prompt",
      "experience-section-title": "Experience",
      "experience-section-note": "Control how the hover entry appears.",
      "toggle-hover-title": "Hover PicPrompt Button",
      "toggle-hover-note": "Show shortcut entry when hovering over images.",
      "toggle-snipping-title": "Shortcut Snipping",
      "toggle-snipping-note": "Use shortcut to select and analyze any area on the page.",
      "toggle-recreate-title": "High-Fidelity Recreation Mode",
      "toggle-recreate-note": "Enable to use detailed analysis prompts for more precise recreation (includes negative prompts and technical parameters).",
      "shortcut-hint": "Default: Alt / Option + S. To modify, go to chrome://extensions/shortcuts",
      "language-label": "Panel Language",
      "language-note": "Switch the language of this settings panel.",
      "compatibility-section-title": "Compatibility",
      "compatibility-section-note": "If you encounter 400 errors, try adjusting these settings.",
      "resolution-label": "Max Image Resolution",
      "resolution-note": "Lowering resolution reduces payload size and avoids timeouts.",
      "reset-button": "Reset to Defaults",
      "preset-general": "General",
      "preset-photo": "📸 Photo",
      "preset-cg": "🎨 Illust",
      "preset-design": "📐 Design",
      "preset-ui": "📱 UI Design",
      "preset-3d": "🧊 3D Asset",
      "preset-product": "👕 Product",
      "preset-anime": "🎭 Anime",
      "preset-architecture": "🏛️ Architecture",
      "preset-food": "🍜 Food",
      "preset-portrait": "👤 Portrait",
      "preset-add-custom": "➕ Add Custom",
      "custom-title-label": "Template Name",
      "custom-title-placeholder": "Name your prompt template",
      "custom-save-btn": "Save",
      "custom-cancel-btn": "Cancel",
      "custom-delete-btn": "🗑️ Delete",
      "footer-contact": "XIhaha: "
    }
  },

  ERROR_CODES: {
    NETWORK_ERROR: "NETWORK_ERROR",
    IMAGE_FETCH_FAILED: "IMAGE_FETCH_FAILED",
    IMAGE_PROCESSING_FAILED: "IMAGE_PROCESSING_FAILED",
    API_AUTH_FAILED: "API_AUTH_FAILED",
    API_RATE_LIMITED: "API_RATE_LIMITED",
    API_TIMEOUT: "API_TIMEOUT",
    API_INVALID_RESPONSE: "API_INVALID_RESPONSE",
    JSON_PARSE_FAILED: "JSON_PARSE_FAILED",
    MISSING_FIELDS: "MISSING_FIELDS",
    CANCELED: "CANCELED",
    UNKNOWN: "UNKNOWN"
  },

  ERROR_MESSAGES: {
    zh: {
      "NETWORK_ERROR": "网络连接失败，请检查网络后重试。",
      "IMAGE_FETCH_FAILED": "无法获取图片，请确认图片链接有效且可访问。",
      "IMAGE_PROCESSING_FAILED": "图片处理失败，请尝试换一张图片或调整分辨率设置。",
      "API_AUTH_FAILED": "API 密钥无效或已过期，请检查设置中的 API Key。",
      "API_RATE_LIMITED": "API 调用次数已达上限，请稍后再试或升级配额。",
      "API_TIMEOUT": "API 请求超时，请检查网络连接或降低图片分辨率。",
      "API_INVALID_RESPONSE": "API 返回了意外结果，请检查模型配置或更换模型。",
      "JSON_PARSE_FAILED": "模型返回的内容无法解析，请调整 System Prompt 确保输出纯 JSON。",
      "MISSING_FIELDS": "模型返回缺少必需的 zh/en 字段，请检查 System Prompt。",
      "CANCELED": "已停止生成。",
      "UNKNOWN": "发生未知错误，请重试。"
    },
    en: {
      "NETWORK_ERROR": "Network connection failed. Please check your connection and try again.",
      "IMAGE_FETCH_FAILED": "Unable to fetch image. Please verify the image URL is valid and accessible.",
      "IMAGE_PROCESSING_FAILED": "Image processing failed. Please try another image or lower the resolution.",
      "API_AUTH_FAILED": "Invalid or expired API key. Please check your API Key in settings.",
      "API_RATE_LIMITED": "API rate limit reached. Please try again later or upgrade your quota.",
      "API_TIMEOUT": "API request timed out. Check your connection or lower image resolution.",
      "API_INVALID_RESPONSE": "API returned unexpected results. Check model configuration or try another model.",
      "JSON_PARSE_FAILED": "Could not parse model output. Adjust System Prompt to ensure pure JSON output.",
      "MISSING_FIELDS": "Model response missing required zh/en fields. Check your System Prompt.",
      "CANCELED": "Generation stopped.",
      "UNKNOWN": "An unknown error occurred. Please try again."
    }
  },

  POSTHOG_PROJECT_KEY: atob("cGhjX3dUYnlxb2FMbnNrUEZFc0t5U0xzdWRiSGFucFR6amJWOGNxWXdEM0ZWeno2"),
  POSTHOG_HOST: "https://us.i.posthog.com",
  ANALYTICS_CONFIG_KEY: "analyticsConfig"
};
